### ISSUE TITLE
Hard-coded, absolute path in `progs.csv`

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [michael-platzer/cv32e40x-soc#1]
The path `/home/michael/Documents/prog/cv32e40x-soc/test.vmem` only works for you.  :wink: 

Also, is `test.vmem` a generated file?  I could not see how that would work.

Thanks!

**Comment by michael-platzer** [comment]
Apologies for that! I added a new target to the Makefile that generates `progs.csv` dynamically (and added it as a dependency to the targets `verilator` and `vivado`). It also generates the `test.vmem` file by invoking `make -f sw/Makefile test.vmem`.

Note that generating the `*.vmem` file requires `srecord` due to a [still unresolved bug in GNU binutils](https://sourceware.org/bugzilla/show_bug.cgi?id=25202).
